language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - openjdk8
  - openjdk11

jobs:
  include:
    - stage: deploy
      jdk: openjdk8
      install:
        - npm install --only=production
        - npx semantic-release
      script: skip
      deploy:
        - provider: script
          script: .travis/deploy-dockerhub-dev.sh
          skip_cleanup: true
          on:
            branch: dev
