komga:
  libraries-scan-cron: "* */15 * * * ?" #periodic scan every 15 minutes
  libraries-scan-directory-exclusions: #patterns to exclude directories from the scan
    - "#recycle" #synology NAS recycle bin
    - "@eaDir"   #synology NAS index/metadata folders
  filesystem-scanner-force-directory-modified-time: false #set to true only if newly added books in existing series are not scanned (ie Google Drive)
  remember-me:
    key: changeMe! #required to activate the remember-me auto-login via cookies
    validity: 2592000 #validity of the cookie in seconds, here 1 month
spring:
  datasource:
    url: jdbc:h2:./komga-database.h2 #database will be located in the current directory
  profiles:
    active: prod
#server:
#  port: 8080 #server port, default is 8080
#  servlet.context-path: /komga #server base url, uncomment if needed
