---
version: '3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - ~/opt/appdata/komga:/config
      - /mnt/nas/media/Books/:/books
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8090:8080
    environment:
      - KOMGA_USER_PASSWORD=your-admin-password
      - KOMGA_ADMIN_PASSWORD=your-user-password
    restart: unless-stopped
