logging.level:
  web: DEBUG
#  org.springframework.security.web.FilterChainProxy: DEBUG
komga:
  root-folder: D:\\files\\pdf
  threads:
    parse: 1
#  root-folder-scan-cron: "*/5 * * * * ?"
spring:
  profiles:
    include: flyway
logging:
  level:
    org.gotson.komga: debug