application.version: ${version}

spring:
  #  cache:
  #    caffeine-spec: maximumSize=500,expireAfterWrite=300s
  h2:
    console:
      enabled: true
  resources:
    cache:
      cachecontrol:
        cache-public: true
        max-age: 365d

server.servlet.session.timeout: 7d

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    health:
      roles: ADMIN
      show-details: when_authorized
  metrics:
    export:
      influx:
        enabled: false
