logging.level:
  web: DEBUG
#  org.springframework.security.web.FilterChainProxy: DEBUG
komga:
  threads:
    parse: 1
#  libraries-scan-directory-exclusions:
#    - "#recycle"
#    - "@eaDir"
#  libraries-scan-cron: "*/5 * * * * ?"
spring:
  profiles:
    include: flyway
logging.file: komga-dev.log
logging:
  file.max-history: 1
  level:
    org.gotson.komga: debug
