komga:
  threads:
    parse: 1
#  libraries-scan-directory-exclusions:
#    - "#recycle"
#    - "@eaDir"
#  libraries-scan-cron: "*/5 * * * * ?"
spring:
  profiles:
    include: flyway
  jpa:
    properties:
      hibernate:
        generate_statistics: true
logging:
  file:
    max-history: 1
    name: komga-dev.log
  level:
    org.gotson.komga: DEBUG
    web: DEBUG
    org.hibernate.stat: DEBUG
    #  org.springframework.security.web.FilterChainProxy: DEBUG
