spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: build/generated/ddl_jpa_creation.sql