komga:
  root-folder: D:\\your\\library\\root\\directory
  root-folder-scan-cron: "* */15 * * * ?" #periodic scan every 15 minutes
  user-password: user-password
  admin-password: admin-password
spring:
  datasource:
    url: jdbc:h2:./komga-database.h2;DB_CLOSE_DELAY=-1 #database will be located in the current directory
  #    url: jdbc:h2:D:\\komga\komga-database.h2;DB_CLOSE_DELAY=-1 #database absolute path, uncomment if necessary and comment above line
  profiles:
    active: prod