name: Deploy to DockerHub

on:
  push:
    branches:
    - master
#     paths:
#     - '*'
#    - '!*.md'
#    - '!.travis.yml'
#    - '!./github/*/*'
#    - '!./doc/*'
#    - '!.idea/runConfigurations/*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - run: ./gradlew build
    - run: echo Triggered by ${{ github.ref }}
